version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_test
    ports:
      - "3306:3306"
    networks:
      - wp-net

  wordpress:
    image: wp-release:builder
    depends_on:
      - mysql
    networks:
      - wp-net
    entrypoint: /bin/sh -c "vendor/bin/phpunit --configuration phpunit.xml.dist"

networks:
  wp-net:
    driver: bridge
