name: E-Commerce container build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted  # The job runs on a self-hosted runner to avoid cost for the case study

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build --cache-from=type=local,src=/tmp/.buildx-cache --target builder -t wp-release:builder .

      - name: Build final Docker image
        run: docker build --cache-from=type=local,src=/tmp/.buildx-cache --target production -t wp-release:${{ env.VERSION }} .

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@latest #v0.24.0
        with:
          image-ref: wp-release:${{ env.VERSION }}

      - name: Run PHP Unit Tests
        run: |
          docker run --rm wp-release:${{ env.VERSION }} vendor/bin/phpunit --configuration phpunit.xml

      # - name: Push Docker image to GCR
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}

      # - name: Configure Docker to use the Google Cloud CLI
      #   run: |
      #     echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io
      #     docker tag wp-release:${{ env.VERSION }} gcr.io/my-gcp-project/wp-release:${{ env.VERSION }}
      #     docker push gcr.io/my-gcp-project/wp-release:${{ env.VERSION }}

      - name: Tag Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: "WordPress Release v${{ env.VERSION }}"
          draft: false
          prerelease: false
